@echo off
cd /d "C:\Users\rokmc\smartech"
echo [Step 0] Copying recordings from Desktop...
robocopy "C:\Users\rokmc\Desktop\통화녹음_임시" "C:\Users\rokmc\smartech\data\녹음" *.m4a *.mp3 *.mp4 *.wav *.aac /MOV /NJH /NJS
echo [Step 1] Transcribing recordings...
node scripts/transcribe-recordings.mjs
echo [Step 2] Running AI pipeline...
node scripts/ai-pipeline.mjs
