export const CATALOG_MAP: Record<string, string> = {
  "오일펌프(소형 RV)":        "/catalogs/1.오일펌프_소형RV.pdf",
  "오일펌프(소형 E2M)":       "/catalogs/1-1.오일펌프_소형E2M.pdf",
  "오일펌프(중대형 E2M)":     "/catalogs/2.오일펌프_중대형E2M.pdf",
  "오일펌프(중대형 E2S)":     "/catalogs/2-1오일펌프 중대형E2S.pdf",
  "오일펌프(nES)":            "/catalogs/3.오일펌프_nES.pdf",
  "스크롤펌프(소형 nXDS)":    "/catalogs/4.스크롤펌프_소형nXDS.pdf",
  "스크롤펌프(중형 XDS)":     "/catalogs/5.스크롤펌프_중형XDS.pdf",
  "부스터펌프(EH)":           "/catalogs/6.부스터펌프EH.pdf",
  "산업용드라이펌프(GXS)":    "/catalogs/7.산업용드라이펌프_GXS Dry.pdf",
  "산업용드라이펌프(EXS)":    "/catalogs/7-1.산업용드라이_EXS.pdf",
  "반도체드라이펌프(iXH)":    "/catalogs/8.반도체드라이_iXH.pdf",
  "반도체드라이펌프(nXRi)":   "/catalogs/8-1.반도체드라이_nXRi.pdf",
  "반도체드라이펌프(iXL)":    "/catalogs/9.반도체드라이_iXL.pdf",
  "헬륨리크디텍터(ELD500)":   "/catalogs/9-1.헬륨리크디텍터_ELD500.pdf",
  "터보펌프(nEXT)":           "/catalogs/10.nEXT 터보펌프.pdf",
  "터보펌프(nEXT Station)":   "/catalogs/11.터보펌프_nEXT_Pumping_Station.pdf",
  "터보펌프(STP)":            "/catalogs/12.터보펌프_STP.pdf",
  "저진공게이지(APG200)":     "/catalogs/13.저진공게이지_APG200.pdf",
  "고진공게이지(AIM200)":     "/catalogs/14.고진공게이지AIM200.pdf",
  "복합진공게이지(WRG200)":   "/catalogs/15.저진공+고진공게이지_WRG200.pdf",
  "디스플레이게이지(P4/P5)":  "/catalogs/16.디스플레이진공게이지_P4-P5.pdf",
  "컨트롤러(TIC)":            "/catalogs/17.컨트롤러_TIC.pdf",
  "컨트롤러(ADC)":            "/catalogs/18.컨트롤러_ADC.pdf",
  "미스트필터(EMF)":          "/catalogs/19.미스트필터(EMF).pdf",
  "진공펌프오일(Ultra19)":    "/catalogs/20.진공펌프오일_Ultra19.pdf",
  "피팅/액세서리":            "/catalogs/21.피팅_52~57페이지사용.PDF",
};
